### PR TITLE
unpin eigen library

### PR DESCRIPTION
**Pull request by ltalirz**
and add test to make sure it actually still works

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ltalirz** [comment]
@kjappelbaum let's wait and see whether it still works with eigen 3.3

after merging this pr you can go ahead with the ARM build

**Comment by kjappelbaum** [comment]
hmm -- it doesn't seem to complain because it found changes in the CI, but because the git-diff failed to run (?) If I run my `git-diff ` (git version 2.36.1) locally in a directory that is not a git repository, it gives error code 127. 129 has been seen before for issues with `git diff` (https://github.com/ocaml/opam/issues/3204).

Only strange that it still worked in https://github.com/conda-forge/zeopp-lsmo-feedstock/runs/7480367605.

**Comment by kjappelbaum** [comment]
ah, now I understand why it worked :D you added the test here :D perhaps, we can change the tests to write to a temporary file and then use the `git diff --no-index`. If you think that makes sense I can make the PR

**Comment by ltalirz** [comment]
sure!

**Comment by ltalirz** [comment]
(or on osx you try to `git add -A` in the tests directory and commit before running the tests)

**Comment by kjappelbaum** [comment]
will check it out locally over the next days, not really clear to me from the logs why it still fails

**Comment by ltalirz** [comment]
I'm ok with merging and fixing this later (this will also make it easy to check it out locally).

We know that the basics work (the program runs, both on linux and osx).

**Pull request merged**
